# Generated by Django 4.1.7 on 2023-02-24 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_proprietaire_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biens',
            name='gestionnaire',
        ),
    ]
